# Generated by Django 2.1.7 on 2019-02-16 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLB_Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MLB_League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MLB_Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MLB_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('team_id', models.IntegerField()),
                ('primary_color', models.CharField(max_length=8)),
                ('secondary_color', models.CharField(max_length=8)),
                ('tertiary_color', models.CharField(max_length=8)),
                ('mlb_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djfb.MLB_Division')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_full', models.CharField(max_length=50)),
                ('name_use', models.CharField(max_length=50)),
                ('name_last', models.CharField(max_length=50)),
                ('position_primary', models.IntegerField()),
                ('height_ft', models.IntegerField()),
                ('height_in', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('throws', models.CharField(max_length=2)),
                ('bats', models.CharField(max_length=2)),
                ('debut', models.DateField()),
                ('birth', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='mlb_league',
            name='mlb_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djfb.MLB_Season'),
        ),
        migrations.AddField(
            model_name='mlb_division',
            name='mlb_league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djfb.MLB_League'),
        ),
    ]
