# Generated by Django 2.1.7 on 2019-02-20 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djfb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batter_Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('hbp', models.IntegerField()),
                ('single', models.IntegerField()),
                ('double', models.IntegerField()),
                ('triple', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('r', models.IntegerField()),
                ('rbi', models.IntegerField()),
                ('sb', models.IntegerField()),
                ('so', models.IntegerField()),
                ('pitcher', models.BooleanField()),
                ('catcher', models.BooleanField()),
                ('first', models.BooleanField()),
                ('second', models.BooleanField()),
                ('third', models.BooleanField()),
                ('short', models.BooleanField()),
                ('left', models.BooleanField()),
                ('center', models.BooleanField()),
                ('right', models.BooleanField()),
                ('dh', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MLB_Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gd_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('away_team_runs', models.IntegerField()),
                ('home_team_runs', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_game_set', to='djfb.MLB_Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_game_set', to='djfb.MLB_Team')),
            ],
        ),
        migrations.CreateModel(
            name='Pitcher_Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w', models.BooleanField()),
                ('l', models.BooleanField()),
                ('sv', models.BooleanField()),
                ('ip', models.IntegerField()),
                ('so', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('h', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('er', models.IntegerField()),
                ('r', models.IntegerField()),
                ('bf', models.IntegerField()),
                ('bk', models.IntegerField()),
                ('game_score', models.IntegerField()),
                ('mlb_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djfb.MLB_Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djfb.Player')),
            ],
        ),
        migrations.AlterModelOptions(
            name='roster',
            options={'ordering': ['player__name_last']},
        ),
        migrations.AddField(
            model_name='batter_game',
            name='mlb_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djfb.MLB_Game'),
        ),
        migrations.AddField(
            model_name='batter_game',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djfb.Player'),
        ),
    ]
