# Generated by Django 2.1.7 on 2019-02-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djfb', '0002_auto_20190220_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlb_game',
            name='losing_team',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='losing_team_game_set', to='djfb.MLB_Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlb_game',
            name='winning_team',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='winning_team_game_set', to='djfb.MLB_Team'),
            preserve_default=False,
        ),
    ]
