# Generated by Django 2.1.7 on 2019-02-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djfb', '0003_auto_20190220_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlb_game',
            name='gd_id',
            field=models.CharField(max_length=50),
        ),
    ]
