# Generated by Django 2.1.7 on 2019-02-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djfb', '0004_auto_20190220_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitcher_game',
            old_name='bk',
            new_name='outs',
        ),
        migrations.RemoveField(
            model_name='pitcher_game',
            name='ip',
        ),
        migrations.AddField(
            model_name='batter_game',
            name='ab',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batter_game',
            name='pa',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
